//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consumer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DatosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Datos", ReplyAction="*")]
        Consumer.ServiceReference1.DatosResponse Datos(Consumer.ServiceReference1.DatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Datos", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumer.ServiceReference1.DatosResponse> DatosAsync(Consumer.ServiceReference1.DatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Datos", Namespace="http://tempuri.org/", Order=0)]
        public Consumer.ServiceReference1.DatosRequestBody Body;
        
        public DatosRequest() {
        }
        
        public DatosRequest(Consumer.ServiceReference1.DatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int dia;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int mes;
        
        public DatosRequestBody() {
        }
        
        public DatosRequestBody(int dia, int mes) {
            this.dia = dia;
            this.mes = mes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumer.ServiceReference1.DatosResponseBody Body;
        
        public DatosResponse() {
        }
        
        public DatosResponse(Consumer.ServiceReference1.DatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DatosResult;
        
        public DatosResponseBody() {
        }
        
        public DatosResponseBody(string DatosResult) {
            this.DatosResult = DatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Consumer.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Consumer.ServiceReference1.WebService1Soap>, Consumer.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumer.ServiceReference1.DatosResponse Consumer.ServiceReference1.WebService1Soap.Datos(Consumer.ServiceReference1.DatosRequest request) {
            return base.Channel.Datos(request);
        }
        
        public string Datos(int dia, int mes) {
            Consumer.ServiceReference1.DatosRequest inValue = new Consumer.ServiceReference1.DatosRequest();
            inValue.Body = new Consumer.ServiceReference1.DatosRequestBody();
            inValue.Body.dia = dia;
            inValue.Body.mes = mes;
            Consumer.ServiceReference1.DatosResponse retVal = ((Consumer.ServiceReference1.WebService1Soap)(this)).Datos(inValue);
            return retVal.Body.DatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumer.ServiceReference1.DatosResponse> Consumer.ServiceReference1.WebService1Soap.DatosAsync(Consumer.ServiceReference1.DatosRequest request) {
            return base.Channel.DatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumer.ServiceReference1.DatosResponse> DatosAsync(int dia, int mes) {
            Consumer.ServiceReference1.DatosRequest inValue = new Consumer.ServiceReference1.DatosRequest();
            inValue.Body = new Consumer.ServiceReference1.DatosRequestBody();
            inValue.Body.dia = dia;
            inValue.Body.mes = mes;
            return ((Consumer.ServiceReference1.WebService1Soap)(this)).DatosAsync(inValue);
        }
    }
}
